module.exports = [
  {
    id: 1,
    patient_id: 1,
    med_name: "Lisinopril",
    med_dose: "10mg",
    med_schedule: 1,
    med_time: "08:00",
    med_taken: false,
    quantity: 30,
  },
  {
    id: 2,
    patient_id: 1,
    med_name: "Metformin",
    med_dose: "500mg",
    med_schedule: 2,
    med_time: "08:00,20:00",
    med_taken: true,
    quantity: 60,
  },
  {
    id: 3,
    patient_id: 2,
    med_name: "Amlodipine",
    med_dose: "5mg",
    med_schedule: 1,
    med_time: "08:00",
    med_taken: false,
    quantity: 30,
  },
  {
    id: 4,
    patient_id: 3,
    med_name: "Atorvastatin",
    med_dose: "20mg",
    med_schedule: 1,
    med_time: "21:00",
    med_taken: true,
    quantity: 30,
  },
];
